apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fyp
  name: fyp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp
  template:
    metadata:
      labels:
        app: fyp
    spec:
      containers:
      - image: rahi776/fyp:latest
        name: fyp
        resources: {}
status: {}