apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp
  labels:
    app: fyp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp
  template:
    metadata:
      labels:
        app: fyp
    spec:
      containers:
      - name: fyp
        image: rahi776/fyp:latest
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fyp-service
spec:
  selector:
    app: fyp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
