name: Staging Pipeline

on:
  push:
    branches:
      - staging

env:
  ENVIRONMENT: staging
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config=env/stg/backend-stg.tfvars

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -var-file=env/stg/stg.tfvars -auto-approve
