name: Delete Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: delete

env:
  ENVIRONMENT: staging
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set env variable
        run: |
          if [ "${{ github.ref }}" = "refs/heads/staging" ]; then
              echo "TF_ENV=stg" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
              echo "TF_ENV=prod" >> $GITHUB_ENV
          fi
      
      - name: Delete Load balancer
        run: |
          sudo apt-get update && sudo apt-get install awscli -y
          aws eks update-kubeconfig --name ${{ env.TF_ENV }}-cluster --region us-east-1
          kubectl delete -f k8s_manifest/deploy.yaml
          sleep 30

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config=env/stg/backend-stg.tfvars

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -var-file=env/stg/stg.tfvars -auto-approve